### ISSUE TITLE
TypeError: Chess is not a constructor

### ISSUE THREAD

**Issue by sk0le** [andyruwruw/chess-web-api#14]
## Steps to reproduce
Just call chessAPI.getGameByID(gameId).then((res) => console.log(res));

## Expected behavior
Get data

## Actual behavior
Error: TypeError: Chess is not a constructor
https://prnt.sc/112ie25

**Comment by andyruwruw** [comment]
Our current test suite is passing so this is curious.

We recently added this endpoint along with `chess.js` as a needed dependency. Can you check that `chess.js` was installed to your node_modules?

**Comment by sk0le** [comment]
https://prnt.sc/1138w38 - package.json
https://prnt.sc/1138wjk - node modules
