### ISSUE TITLE
getGameByID only works with live games

### ISSUE THREAD

**Issue by Cristian-A** [andyruwruw/chess-web-api#20]
#### chess-web-api version:
latest

## Steps to reproduce
Call getGameByID and get the result

## Expected behavior
The getGameByID returns a live game

## Actual behavior
The `getGameByID` should have returned a daily game instead.
Since the IDs for live-chess and daily-chess can overlap, I suggest dividing this method in `getLiveGameByID` and `getDailyGameByID`.

This is your code, I believe you can change `/callback/live/game/${id}` to `/callback/daily/game/${id}` to get the desired output.

``` js
// line 178, endpoint/games.js
const apiRequest = WebApiRequest.builder()
    .withHost(UNDOCUMENTED_API_HOST)
    .withPath(`/callback/live/game/${id}`)
    .withQueryParameters(_options)
    .withHeaders(_headers)
    .build();
```

**Comment by andyruwruw** [comment]
Good idea, I'll have to see if that endpoint exists as it is undocumented and not intended for 3rd party use. But if it works that'd be a great addition.

**Comment by Cristian-A** [comment]
thanks, that would be great!

**Comment by andyruwruw** [comment]
Sadly having no luck finding a suitable endpoint for live matches. My assumption is it uses web sockets to retrieve and update moves. If you have any luck finding and unofficial endpoints, let me know!
