### ISSUE TITLE
Setting callbackParameters in dispatch function throws error

### ISSUE THREAD

**Issue by AntonioDrk** [andyruwruw/chess-web-api#24]
Hi! 👋 
      
Firstly, thanks for your work on this project I love it! 🙂

Unfortunately I had to patch the module for the `dispatch()` function, more concretely having callback function params would not work.
To replicate: Running the code in the example of dispatch doesn't work and gives off an unhandled promise rejection error. Which is tied to the way `sortParameters` is called.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/chess-web-api/src/queue/index.js b/node_modules/chess-web-api/src/queue/index.js
index aaf838e..9217bb4 100644
--- a/node_modules/chess-web-api/src/queue/index.js
+++ b/node_modules/chess-web-api/src/queue/index.js
@@ -27,7 +27,7 @@ function dispatch(method, callback, parameters, options, callbackParameters, pri
   }
 
   const [_parameters, _options, _callbackParameters, _priority] = sortParameters(
-    ['array', 'object', 'function', 'number'],
+    ['array', 'object', 'array', 'number'],
     [parameters, options, callbackParameters, priority],
   );
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by andyruwruw** [comment]
Great catch, can't believe that error sat there for that long. I've fixed it and published the change in `v1.1.2`. Thanks for finding that!
