### ISSUE TITLE
Breaking Change: User-Agent Contact Info Required

### ISSUE THREAD

**Issue by ddugovic** [andyruwruw/chess-web-api#35]
Chess.com announced an API break.  How do I set my user-agent?
https://www.chess.com/news/view/breaking-change-user-agent-contact-info-required

#### chess-web-api version:
latest

## Steps to reproduce
```
    const api = new ChessWebAPI();
    console.log(api.getPlayer('toadofsky'));
```
 
## Expected behavior
Get results

## Actual behavior
`WebapiError: Forbidden`

**Comment by PabloJavArrVel** [comment]
What a sad thing, it literally stops my project. Hope we get a solution soon

**Comment by ddugovic** [comment]
Yeah... I tried quite a few things to be able to send a `user-agent` header, but nothing I tried worked since apparently your "headers" options don't work.

**Comment by andyruwruw** [comment]
Oh shoot, that isn't good. Will get on that ASAP.

**Comment by ddugovic** [comment]
Thanks, we'll look forward to it.

**Comment by JujuDel** [comment]
Just discovered this nice API and faced the issue as well :)

It obviously made your nice README not working when not mocking the data but using live one: https://github.com/andyruwruw/andyruwruw/issues/20

Would you mind refactoring your `sortParameters` function in `src/utils/sort-parameters.js` to allow us to pass a value for the header in the request?

It would be neat if one could simply do `getPlayer(username, {'User-Agent':'hello@gmail.com'})` (or even `getPlayer(username, undefined, undefined, {'User-Agent':'hello@gmail.com'})` would work for me to)
