### ISSUE TITLE
Spelling Error in Readme "Priority Queue" Section

### ISSUE THREAD

**Issue by shreyas-girjapure** [andyruwruw/chess-web-api#5]
## Steps to reproduce
1. Open Readme file.
1. Search for string 'inicialize'.
1. 2 occurrences can be found 'inicialize' and 'inicialized'.

## Expected behavior
Spelling should have been "initialize" or "initialized".
## Actual behavior
Now it is "inicialized" and "inicialize".

This is really a small change , Posted in contribution to make the documentation error-free and awsome💯

**Comment by shreyas-girjapure** [comment]
I am working on it.

**Comment by shreyas-girjapure** [comment]
I have created a pull request regarding it. Can you please look into it.
Thanks,
-Shreyas

**Comment by andyruwruw** [comment]
Thank you!!
